/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class msl_com_interactivejob_JNIHelper */

#ifndef _Included_msl_com_interactivejob_JNIHelper
#define _Included_msl_com_interactivejob_JNIHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     msl_com_interactivejob_JNIHelper
 * Method:    test
 * Signature: (Ljava/lang/String;Ljava/lang/String;JF)[F
 */
JNIEXPORT jfloatArray JNICALL Java_msl_com_interactivejob_JNIHelper_test
  (JNIEnv *, jobject, jstring, jstring, jlong, jfloat);

#ifdef __cplusplus
}
#endif
#endif
